CREATE SEQUENCE SEQ_CONTINENT
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 9999999;

CREATE TABLE T_CONTINENT 
   (	
	KEY INTEGER NOT NULL, 
	NAME VARCHAR(20), 
	CODE VARCHAR(20)
   );

ALTER TABLE T_CONTINENT
ADD CONSTRAINT PK_CONTINENT PRIMARY KEY (KEY);